package julio.tactics.regras.GURPS.IA
{
	/**
	 * ...
	 * @author Júlio Cézar
	 */
	public class Gambit
	{
		public static const SELF:Array = [
							EIA_Condition.HP_gt_10_p,
							EIA_Condition.HP_gt_20_p,
							EIA_Condition.HP_gt_30_p,
							EIA_Condition.HP_gt_40_p,
							EIA_Condition.HP_gt_50_p,
							EIA_Condition.HP_gt_60_p,
							EIA_Condition.HP_gt_70_p,
							EIA_Condition.HP_gt_80_p,
							EIA_Condition.HP_gt_90_p,
							EIA_Condition.HP_lt_90_p,
							EIA_Condition.HP_lt_80_p,
							EIA_Condition.HP_lt_70_p,
							EIA_Condition.HP_lt_60_p,
							EIA_Condition.HP_lt_50_p,
							EIA_Condition.HP_lt_40_p,
							EIA_Condition.HP_lt_30_p,
							EIA_Condition.HP_lt_20_p,
							EIA_Condition.HP_lt_10_p,
							EIA_Condition.MP_gt_10_p,
							EIA_Condition.MP_gt_20_p,
							EIA_Condition.MP_gt_30_p,
							EIA_Condition.MP_gt_40_p,
							EIA_Condition.MP_gt_50_p,
							EIA_Condition.MP_gt_60_p,
							EIA_Condition.MP_gt_70_p,
							EIA_Condition.MP_gt_80_p,
							EIA_Condition.MP_gt_90_p,
							EIA_Condition.MP_lt_90_p,
							EIA_Condition.MP_lt_80_p,
							EIA_Condition.MP_lt_70_p,
							EIA_Condition.MP_lt_60_p,
							EIA_Condition.MP_lt_50_p,
							EIA_Condition.MP_lt_40_p,
							EIA_Condition.MP_lt_30_p,
							EIA_Condition.MP_lt_20_p,
							EIA_Condition.MP_lt_10_p,
							EIA_Condition.STATUS_any,
							EIA_Condition.STATUS_any_debuff,
							EIA_Condition.STATUS_any_buff,
							EIA_Condition.STATUS_KO,
							EIA_Condition.STATUS_bloodied,
							EIA_Condition.STATUS_near_death,
							EIA_Condition.STATUS_Passive,
							EIA_Condition.STATUS_Bravery,
							EIA_Condition.STATUS_Fear,
							EIA_Condition.STATUS_Defaith,
							EIA_Condition.STATUS_Sleep,
/*							EIA_Condition.STATUS_Confuse,
							EIA_Condition.STATUS_Blind,
							EIA_Condition.STATUS_Poison,
							EIA_Condition.STATUS_Silence,
							EIA_Condition.STATUS_Immobilize,
							EIA_Condition.STATUS_Slow,
							EIA_Condition.STATUS_Protect,
							EIA_Condition.STATUS_Shell,
							EIA_Condition.STATUS_Haste,
							EIA_Condition.STATUS_Invisible,
							EIA_Condition.STATUS_Regen,
							EIA_Condition.STATUS_Berserk,*/
							EIA_Condition.ELEMENTAL_FIRE_WEAK,
							EIA_Condition.ELEMENTAL_WIND_WEAK,
							EIA_Condition.ELEMENTAL_WATER_WEAK,
							EIA_Condition.ELEMENTAL_EARTH_WEAK,
							EIA_Condition.ELEMENTAL_LIGHT_WEAK,
							EIA_Condition.ELEMENTAL_DEAK_WEAK,
							EIA_Condition.ELEMENTAL_FIRE_VULNERABLE,
							EIA_Condition.ELEMENTAL_WIND_VULNERABLE,
							EIA_Condition.ELEMENTAL_WATER_VULNERABLE,
							EIA_Condition.ELEMENTAL_EARTH_VULNERABLE,
							EIA_Condition.ELEMENTAL_LIGHT_VULNERABLE,
							EIA_Condition.ELEMENTAL_DEAK_VULNERABLE,
							EIA_Condition.UNDEAD,
							EIA_Condition.FLYING,
							EIA_Condition.HAS_ITEM];
		
		
		public static const ALLY:Array = [
							EIA_Condition.HIGHEST_HP,
							EIA_Condition.LOWEST_HP,
							EIA_Condition.HIGHEST_MP,
							EIA_Condition.LOWEST_MP,
							EIA_Condition.HIGHEST_MAX_HP,
							EIA_Condition.LOWEST_MAX_HP,
							EIA_Condition.HIGHEST_MAX_MP,
							EIA_Condition.LOWES_MAXT_MP,
							EIA_Condition.HIGHEST_LEVEL,
							EIA_Condition.LOWEST_LEVEL,
							EIA_Condition.HIGHEST_ATTACK_POWER,
							EIA_Condition.LOWEST_ATTACK_POWER,
							EIA_Condition.HIGHEST_MAGIC_POWER,
							EIA_Condition.LOWEST_MAGIC_POWER,
							EIA_Condition.HIGHEST_DEFENSE,
							EIA_Condition.LOWEST_DEFENSE,
							EIA_Condition.HIGHEST_MAGIC_DEFENSE,
							EIA_Condition.LOWEST_MAGIC_DEFENSE,
							EIA_Condition.HIGHEST_STATUS_DEFENSE,
							EIA_Condition.LOWEST_STATUS_DEFENSE,
							EIA_Condition.HIGHEST_SPEED,
							EIA_Condition.LOWEST_SPEED,
							EIA_Condition.HP_gt_10_p,
							EIA_Condition.HP_gt_20_p,
							EIA_Condition.HP_gt_30_p,
							EIA_Condition.HP_gt_40_p,
							EIA_Condition.HP_gt_50_p,
							EIA_Condition.HP_gt_60_p,
							EIA_Condition.HP_gt_70_p,
							EIA_Condition.HP_gt_80_p,
							EIA_Condition.HP_gt_90_p,
							EIA_Condition.HP_lt_90_p,
							EIA_Condition.HP_lt_80_p,
							EIA_Condition.HP_lt_70_p,
							EIA_Condition.HP_lt_60_p,
							EIA_Condition.HP_lt_50_p,
							EIA_Condition.HP_lt_40_p,
							EIA_Condition.HP_lt_30_p,
							EIA_Condition.HP_lt_20_p,
							EIA_Condition.HP_lt_10_p,
							EIA_Condition.MP_gt_10_p,
							EIA_Condition.MP_gt_20_p,
							EIA_Condition.MP_gt_30_p,
							EIA_Condition.MP_gt_40_p,
							EIA_Condition.MP_gt_50_p,
							EIA_Condition.MP_gt_60_p,
							EIA_Condition.MP_gt_70_p,
							EIA_Condition.MP_gt_80_p,
							EIA_Condition.MP_gt_90_p,
							EIA_Condition.MP_lt_90_p,
							EIA_Condition.MP_lt_80_p,
							EIA_Condition.MP_lt_70_p,
							EIA_Condition.MP_lt_60_p,
							EIA_Condition.MP_lt_50_p,
							EIA_Condition.MP_lt_40_p,
							EIA_Condition.MP_lt_30_p,
							EIA_Condition.MP_lt_20_p,
							EIA_Condition.MP_lt_10_p,
							EIA_Condition.STATUS_any,
							EIA_Condition.STATUS_any_debuff,
							EIA_Condition.STATUS_any_buff,
							EIA_Condition.STATUS_KO,
							EIA_Condition.STATUS_bloodied,
							EIA_Condition.STATUS_near_death,
							EIA_Condition.STATUS_Passive,
							EIA_Condition.STATUS_Bravery,
							EIA_Condition.STATUS_Fear,
							EIA_Condition.STATUS_Defaith,
							EIA_Condition.STATUS_Sleep,
/*							EIA_Condition.STATUS_Confuse,
							EIA_Condition.STATUS_Blind,
							EIA_Condition.STATUS_Poison,
							EIA_Condition.STATUS_Silence,
							EIA_Condition.STATUS_Immobilize,
							EIA_Condition.STATUS_Slow,
							EIA_Condition.STATUS_Protect,
							EIA_Condition.STATUS_Shell,
							EIA_Condition.STATUS_Haste,
							EIA_Condition.STATUS_Invisible,
							EIA_Condition.STATUS_Regen,
							EIA_Condition.STATUS_Berserk,*/
							EIA_Condition.ELEMENTAL_FIRE_WEAK,
							EIA_Condition.ELEMENTAL_WIND_WEAK,
							EIA_Condition.ELEMENTAL_WATER_WEAK,
							EIA_Condition.ELEMENTAL_EARTH_WEAK,
							EIA_Condition.ELEMENTAL_LIGHT_WEAK,
							EIA_Condition.ELEMENTAL_DEAK_WEAK,
							EIA_Condition.ELEMENTAL_FIRE_VULNERABLE,
							EIA_Condition.ELEMENTAL_WIND_VULNERABLE,
							EIA_Condition.ELEMENTAL_WATER_VULNERABLE,
							EIA_Condition.ELEMENTAL_EARTH_VULNERABLE,
							EIA_Condition.ELEMENTAL_LIGHT_VULNERABLE,
							EIA_Condition.ELEMENTAL_DEAK_VULNERABLE,
							EIA_Condition.UNDEAD,
							EIA_Condition.FLYING,
							EIA_Condition.SELF_HAS_ITEM,
							EIA_Condition.ANY,
							EIA_Condition.NEAREST,
							EIA_Condition.FURTHEST,
							EIA_Condition.SELF_HP_gt_10_p,
							EIA_Condition.SELF_HP_gt_20_p,
							EIA_Condition.SELF_HP_gt_30_p,
							EIA_Condition.SELF_HP_gt_40_p,
							EIA_Condition.SELF_HP_gt_50_p,
							EIA_Condition.SELF_HP_gt_60_p,
							EIA_Condition.SELF_HP_gt_70_p,
							EIA_Condition.SELF_HP_gt_80_p,
							EIA_Condition.SELF_HP_gt_90_p,
							EIA_Condition.SELF_HP_lt_90_p,
							EIA_Condition.SELF_HP_lt_80_p,
							EIA_Condition.SELF_HP_lt_70_p,
							EIA_Condition.SELF_HP_lt_60_p,
							EIA_Condition.SELF_HP_lt_50_p,
							EIA_Condition.SELF_HP_lt_40_p,
							EIA_Condition.SELF_HP_lt_30_p,
							EIA_Condition.SELF_HP_lt_20_p,
							EIA_Condition.SELF_HP_lt_10_p,
							EIA_Condition.SELF_MP_gt_10_p,
							EIA_Condition.SELF_MP_gt_20_p,
							EIA_Condition.SELF_MP_gt_30_p,
							EIA_Condition.SELF_MP_gt_40_p,
							EIA_Condition.SELF_MP_gt_50_p,
							EIA_Condition.SELF_MP_gt_60_p,
							EIA_Condition.SELF_MP_gt_70_p,
							EIA_Condition.SELF_MP_gt_80_p,
							EIA_Condition.SELF_MP_gt_90_p,
							EIA_Condition.SELF_MP_lt_90_p,
							EIA_Condition.SELF_MP_lt_80_p,
							EIA_Condition.SELF_MP_lt_70_p,
							EIA_Condition.SELF_MP_lt_60_p,
							EIA_Condition.SELF_MP_lt_50_p,
							EIA_Condition.SELF_MP_lt_40_p,
							EIA_Condition.SELF_MP_lt_30_p,
							EIA_Condition.SELF_MP_lt_20_p,
							EIA_Condition.SELF_MP_lt_10_p,
							EIA_Condition.SELF_STATUS_any,
							EIA_Condition.SELF_STATUS_any_debuff,
							EIA_Condition.SELF_STATUS_any_buff,
							EIA_Condition.SELF_STATUS_KO,
							EIA_Condition.SELF_STATUS_bloodied,
							EIA_Condition.SELF_STATUS_near_death,
							EIA_Condition.SELF_STATUS_Passive,
							EIA_Condition.SELF_STATUS_Bravery,
							EIA_Condition.SELF_STATUS_Fear,
							EIA_Condition.SELF_STATUS_Defaith,
							EIA_Condition.SELF_STATUS_Sleep
/*							EIA_Condition.SELF_STATUS_Confuse,
							EIA_Condition.SELF_STATUS_Blind,
							EIA_Condition.SELF_STATUS_Poison,
							EIA_Condition.SELF_STATUS_Silence,
							EIA_Condition.SELF_STATUS_Immobilize,
							EIA_Condition.SELF_STATUS_Slow,
							EIA_Condition.SELF_STATUS_Protect,
							EIA_Condition.SELF_STATUS_Shell,
							EIA_Condition.SELF_STATUS_Haste,
							EIA_Condition.SELF_STATUS_Invisible,
							EIA_Condition.SELF_STATUS_Regen,
							EIA_Condition.SELF_STATUS_Berserk*/];
		
		
		public static const FOE:Array = [
							EIA_Condition.HIGHEST_HP,
							EIA_Condition.LOWEST_HP,
							EIA_Condition.HIGHEST_MP,
							EIA_Condition.LOWEST_MP,
							EIA_Condition.HIGHEST_MAX_HP,
							EIA_Condition.LOWEST_MAX_HP,
							EIA_Condition.HIGHEST_MAX_MP,
							EIA_Condition.LOWES_MAXT_MP,
							EIA_Condition.HIGHEST_LEVEL,
							EIA_Condition.LOWEST_LEVEL,
							EIA_Condition.HIGHEST_ATTACK_POWER,
							EIA_Condition.LOWEST_ATTACK_POWER,
							EIA_Condition.HIGHEST_MAGIC_POWER,
							EIA_Condition.LOWEST_MAGIC_POWER,
							EIA_Condition.HIGHEST_DEFENSE,
							EIA_Condition.LOWEST_DEFENSE,
							EIA_Condition.HIGHEST_MAGIC_DEFENSE,
							EIA_Condition.LOWEST_MAGIC_DEFENSE,
							EIA_Condition.HIGHEST_STATUS_DEFENSE,
							EIA_Condition.LOWEST_STATUS_DEFENSE,
							EIA_Condition.HIGHEST_SPEED,
							EIA_Condition.LOWEST_SPEED,
							EIA_Condition.HP_gt_10_p,
							EIA_Condition.HP_gt_20_p,
							EIA_Condition.HP_gt_30_p,
							EIA_Condition.HP_gt_40_p,
							EIA_Condition.HP_gt_50_p,
							EIA_Condition.HP_gt_60_p,
							EIA_Condition.HP_gt_70_p,
							EIA_Condition.HP_gt_80_p,
							EIA_Condition.HP_gt_90_p,
							EIA_Condition.HP_lt_90_p,
							EIA_Condition.HP_lt_80_p,
							EIA_Condition.HP_lt_70_p,
							EIA_Condition.HP_lt_60_p,
							EIA_Condition.HP_lt_50_p,
							EIA_Condition.HP_lt_40_p,
							EIA_Condition.HP_lt_30_p,
							EIA_Condition.HP_lt_20_p,
							EIA_Condition.HP_lt_10_p,
							EIA_Condition.MP_gt_10_p,
							EIA_Condition.MP_gt_20_p,
							EIA_Condition.MP_gt_30_p,
							EIA_Condition.MP_gt_40_p,
							EIA_Condition.MP_gt_50_p,
							EIA_Condition.MP_gt_60_p,
							EIA_Condition.MP_gt_70_p,
							EIA_Condition.MP_gt_80_p,
							EIA_Condition.MP_gt_90_p,
							EIA_Condition.MP_lt_90_p,
							EIA_Condition.MP_lt_80_p,
							EIA_Condition.MP_lt_70_p,
							EIA_Condition.MP_lt_60_p,
							EIA_Condition.MP_lt_50_p,
							EIA_Condition.MP_lt_40_p,
							EIA_Condition.MP_lt_30_p,
							EIA_Condition.MP_lt_20_p,
							EIA_Condition.MP_lt_10_p,
							EIA_Condition.STATUS_any,
							EIA_Condition.STATUS_any_debuff,
							EIA_Condition.STATUS_any_buff,
							EIA_Condition.STATUS_KO,
							EIA_Condition.STATUS_bloodied,
							EIA_Condition.STATUS_near_death,
							EIA_Condition.STATUS_Passive,
							EIA_Condition.STATUS_Bravery,
							EIA_Condition.STATUS_Fear,
							EIA_Condition.STATUS_Defaith,
							EIA_Condition.STATUS_Sleep,
/*							EIA_Condition.STATUS_Confuse,
							EIA_Condition.STATUS_Blind,
							EIA_Condition.STATUS_Poison,
							EIA_Condition.STATUS_Silence,
							EIA_Condition.STATUS_Immobilize,
							EIA_Condition.STATUS_Slow,
							EIA_Condition.STATUS_Protect,
							EIA_Condition.STATUS_Shell,
							EIA_Condition.STATUS_Haste,
							EIA_Condition.STATUS_Invisible,
							EIA_Condition.STATUS_Regen,
							EIA_Condition.STATUS_Berserk,*/
							EIA_Condition.ELEMENTAL_FIRE_WEAK,
							EIA_Condition.ELEMENTAL_WIND_WEAK,
							EIA_Condition.ELEMENTAL_WATER_WEAK,
							EIA_Condition.ELEMENTAL_EARTH_WEAK,
							EIA_Condition.ELEMENTAL_LIGHT_WEAK,
							EIA_Condition.ELEMENTAL_DEAK_WEAK,
							EIA_Condition.ELEMENTAL_FIRE_VULNERABLE,
							EIA_Condition.ELEMENTAL_WIND_VULNERABLE,
							EIA_Condition.ELEMENTAL_WATER_VULNERABLE,
							EIA_Condition.ELEMENTAL_EARTH_VULNERABLE,
							EIA_Condition.ELEMENTAL_LIGHT_VULNERABLE,
							EIA_Condition.ELEMENTAL_DEAK_VULNERABLE,
							EIA_Condition.UNDEAD,
							EIA_Condition.FLYING,
							EIA_Condition.HAS_ITEM,
							EIA_Condition.SELF_HAS_ITEM,
							EIA_Condition.PARTY_LEADER_TARGET,
							EIA_Condition.ANY,
							EIA_Condition.NEAREST,
							EIA_Condition.FURTHEST,
							EIA_Condition.ENEMY_LEADER,
							EIA_Condition.SELF_HP_gt_10_p,
							EIA_Condition.SELF_HP_gt_20_p,
							EIA_Condition.SELF_HP_gt_30_p,
							EIA_Condition.SELF_HP_gt_40_p,
							EIA_Condition.SELF_HP_gt_50_p,
							EIA_Condition.SELF_HP_gt_60_p,
							EIA_Condition.SELF_HP_gt_70_p,
							EIA_Condition.SELF_HP_gt_80_p,
							EIA_Condition.SELF_HP_gt_90_p,
							EIA_Condition.SELF_HP_lt_90_p,
							EIA_Condition.SELF_HP_lt_80_p,
							EIA_Condition.SELF_HP_lt_70_p,
							EIA_Condition.SELF_HP_lt_60_p,
							EIA_Condition.SELF_HP_lt_50_p,
							EIA_Condition.SELF_HP_lt_40_p,
							EIA_Condition.SELF_HP_lt_30_p,
							EIA_Condition.SELF_HP_lt_20_p,
							EIA_Condition.SELF_HP_lt_10_p,
							EIA_Condition.SELF_MP_gt_10_p,
							EIA_Condition.SELF_MP_gt_20_p,
							EIA_Condition.SELF_MP_gt_30_p,
							EIA_Condition.SELF_MP_gt_40_p,
							EIA_Condition.SELF_MP_gt_50_p,
							EIA_Condition.SELF_MP_gt_60_p,
							EIA_Condition.SELF_MP_gt_70_p,
							EIA_Condition.SELF_MP_gt_80_p,
							EIA_Condition.SELF_MP_gt_90_p,
							EIA_Condition.SELF_MP_lt_90_p,
							EIA_Condition.SELF_MP_lt_80_p,
							EIA_Condition.SELF_MP_lt_70_p,
							EIA_Condition.SELF_MP_lt_60_p,
							EIA_Condition.SELF_MP_lt_50_p,
							EIA_Condition.SELF_MP_lt_40_p,
							EIA_Condition.SELF_MP_lt_30_p,
							EIA_Condition.SELF_MP_lt_20_p,
							EIA_Condition.SELF_MP_lt_10_p,
							EIA_Condition.SELF_STATUS_any,
							EIA_Condition.SELF_STATUS_any_debuff,
							EIA_Condition.SELF_STATUS_any_buff,
							EIA_Condition.SELF_STATUS_KO,
							EIA_Condition.SELF_STATUS_bloodied,
							EIA_Condition.SELF_STATUS_near_death,
							EIA_Condition.SELF_STATUS_Passive,
							EIA_Condition.SELF_STATUS_Bravery,
							EIA_Condition.SELF_STATUS_Fear,
							EIA_Condition.SELF_STATUS_Defaith,
							EIA_Condition.SELF_STATUS_Sleep
/*							EIA_Condition.SELF_STATUS_Confuse,
							EIA_Condition.SELF_STATUS_Blind,
							EIA_Condition.SELF_STATUS_Poison,
							EIA_Condition.SELF_STATUS_Silence,
							EIA_Condition.SELF_STATUS_Immobilize,
							EIA_Condition.SELF_STATUS_Slow,
							EIA_Condition.SELF_STATUS_Protect,
							EIA_Condition.SELF_STATUS_Shell,
							EIA_Condition.SELF_STATUS_Haste,
							EIA_Condition.SELF_STATUS_Invisible,
							EIA_Condition.SELF_STATUS_Regen,
							EIA_Condition.SELF_STATUS_Berserk*/];
		
		
		private var _target:EIA_Target;		// alvo
		private var _conditions:Array;		// lista de condições
		private var _action:String;			// id da ação
		
		public function Gambit( target:EIA_Target, conditions:Array, action:String )
		{
			this.action = action;
			this.target = target;
			
			for each( var c:EIA_Condition in conditions )
				addCondition(c);
		}
		
		public function get target():EIA_Target { return this._target; }
		public function set target( value:EIA_Target):void { this._target = value; this._conditions = []; }
		
		public function addCondition( value:EIA_Condition ):void
		{
			if ( target == EIA_Target.SELF )
				if ( SELF.indexOf( value ) == -1 )
					throw new Error("Erro em Gambit::addCondition( "+value+" ). Essa condição não é valida em SELF");
			if ( target == EIA_Target.ALLY )
				if ( ALLY.indexOf( value ) == -1 )
					throw new Error("Erro em Gambit::addCondition( "+value+" ). Essa condição não é valida em ALLY");
			if ( target == EIA_Target.FOE )
				if ( FOE.indexOf( value ) == -1 )
					throw new Error("Erro em Gambit::addCondition( "+value+" ). Essa condição não é valida em FOE");
			
			this._conditions.push( value );
		}
		public function removeCondition( value:EIA_Condition ):void
		{
			this._conditions.splice( this._conditions.indexOf(value), 1 );
		}
		
		public function get action():String { return this._action; }
		public function set action( value:String):void { this._action = value; }
	}

}
